---
title: "test"
author: "Your name"
date: '2022-05-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

|  Name     |       Description                     |    Levels                   |
|:---------:|    :-----------------------------:    |  :------------------------: |
|   Age     |        Age of the patient             |       28 yrs - 77 yrs       |
|   Sex     |        Sex of the patient             |       Male, Female          |
|   exang   |        exercise induced angina        |       (1 = yes; 0 = no)     |
|   caa     |        number of major vessels        |       (0-3)                 |
|   cp      |        Chest Pain type chest pain type|       Value 1: typical angina   [TA] |
|           |                                       |       Value 2: atypical angina  [ATA]|
|           |                                       |       Value 3: non-anginal pain [NAP]|
|           |                                       |       Value 4: asymptomatic     [ASY]|
|   trtbps  |     resting blood pressure (in mm Hg) |       0 - 200 mm Hg                       |
|   chol    |   cholestoral in mg/dl fetched via BMI sensor |   0-603 mg/dl                     |
|   fbs     |        (fasting blood sugar > 120 mg/dl) |        (1 = true; 0 = false)      |   
|   rest_ecg|        resting electrocardiographic results   |  Value 0: normal              |
|           |                                       |          Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or  |  |           |                                       |          depression of > 0.05 mV)                                                         |
|           |                                       |     Value 2: showing probable or definite left ventricular hypertrophy by Estes'  criteria |
|   thalach |       maximum heart rate achieved     |       60 - 202 bpm                              |
|   target  |        chance of a heart attack       |       0= less chance of heart attack; 1= more chance of heart attack |                                                           

------------------------------------------------------------------------------------------------------------------------------------------------

# Chest Type 

## Chest Type

#### Chest type


